# Training configuration
vocab_path: dataset/wikitext/vocab.json
finetune_data_path: dataset/treebank
n_classes: 38
device: cuda
lr: 0.001

Train:
  batch_size: 4048
  shuffle: True
  num_workers: 8
  pin_memory: False
  max_len: 64
  resume: False
  epochs: 500

Eval:
  batch_size: 2048
  shuffle: True
  num_workers: 8
  pin_memory: False

# Model configuration
num_hiddens: 128
ffn_num_hiddens: 256
num_heads: 2
num_blks: 2
dropout: 0.2
max_len: 64

# Debugging
log_file: logs/finetune/text_tagging.log
tensorboard: debugs/tensorboard/text_tagging

finetune_checkpoints: 
  best_ckpt_path: weights/finetune_text_tagging/best.pth
  last_ckpt_path: weights/finetune_text_tagging/last.pth

pretrain_checkpoints:
  best_ckpt_path: weights/pretrain/best.pth
  last_ckpt_path: weights/pretrain/last.pth
  